### ISSUE TITLE
Generate site id method need to be dynamic for Year and locality part

### ISSUE THREAD

**Issue by mohammad-oghli** [Archireef/Reef-DataOps#7]
https://github.com/Archireef/Reef-DataOps/blob/6c1f6e49d8e31a2f73e06b9e7645b7cc3f3e6907/src/pages/5_Create_Site.py#L64

**Comment by medo-younes** [comment]
Resolved this issue here - https://github.com/Archireef/Reef-DataOps/commit/38841c286aa4ac78840afbf8078b262cb87fccd0
